// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_protobuf.proto

#ifndef PROTOBUF_db_5fprotobuf_2eproto__INCLUDED
#define PROTOBUF_db_5fprotobuf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "db_protobuf_struct.pb.h"
// @@protoc_insertion_point(includes)

namespace db_protobuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_db_5fprotobuf_2eproto();
void protobuf_InitDefaults_db_5fprotobuf_2eproto();
void protobuf_AssignDesc_db_5fprotobuf_2eproto();
void protobuf_ShutdownFile_db_5fprotobuf_2eproto();

class db_loginallserverinfo;

// ===================================================================

class db_loginallserverinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:db_protobuf.db_loginallserverinfo) */ {
 public:
  db_loginallserverinfo();
  virtual ~db_loginallserverinfo();

  db_loginallserverinfo(const db_loginallserverinfo& from);

  inline db_loginallserverinfo& operator=(const db_loginallserverinfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const db_loginallserverinfo& default_instance();

  static const db_loginallserverinfo* internal_default_instance();

  void Swap(db_loginallserverinfo* other);

  // implements Message ----------------------------------------------

  inline db_loginallserverinfo* New() const { return New(NULL); }

  db_loginallserverinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const db_loginallserverinfo& from);
  void MergeFrom(const db_loginallserverinfo& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(db_loginallserverinfo* other);
  void UnsafeMergeFrom(const db_loginallserverinfo& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .db_protobuf.serverinfo allserverinfo = 1;
  int allserverinfo_size() const;
  void clear_allserverinfo();
  static const int kAllserverinfoFieldNumber = 1;
  const ::db_protobuf::serverinfo& allserverinfo(int index) const;
  ::db_protobuf::serverinfo* mutable_allserverinfo(int index);
  ::db_protobuf::serverinfo* add_allserverinfo();
  ::google::protobuf::RepeatedPtrField< ::db_protobuf::serverinfo >*
      mutable_allserverinfo();
  const ::google::protobuf::RepeatedPtrField< ::db_protobuf::serverinfo >&
      allserverinfo() const;

  // @@protoc_insertion_point(class_scope:db_protobuf.db_loginallserverinfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::db_protobuf::serverinfo > allserverinfo_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_db_5fprotobuf_2eproto_impl();
  friend void  protobuf_AddDesc_db_5fprotobuf_2eproto_impl();
  friend void protobuf_AssignDesc_db_5fprotobuf_2eproto();
  friend void protobuf_ShutdownFile_db_5fprotobuf_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<db_loginallserverinfo> db_loginallserverinfo_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// db_loginallserverinfo

// repeated .db_protobuf.serverinfo allserverinfo = 1;
inline int db_loginallserverinfo::allserverinfo_size() const {
  return allserverinfo_.size();
}
inline void db_loginallserverinfo::clear_allserverinfo() {
  allserverinfo_.Clear();
}
inline const ::db_protobuf::serverinfo& db_loginallserverinfo::allserverinfo(int index) const {
  // @@protoc_insertion_point(field_get:db_protobuf.db_loginallserverinfo.allserverinfo)
  return allserverinfo_.Get(index);
}
inline ::db_protobuf::serverinfo* db_loginallserverinfo::mutable_allserverinfo(int index) {
  // @@protoc_insertion_point(field_mutable:db_protobuf.db_loginallserverinfo.allserverinfo)
  return allserverinfo_.Mutable(index);
}
inline ::db_protobuf::serverinfo* db_loginallserverinfo::add_allserverinfo() {
  // @@protoc_insertion_point(field_add:db_protobuf.db_loginallserverinfo.allserverinfo)
  return allserverinfo_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::db_protobuf::serverinfo >*
db_loginallserverinfo::mutable_allserverinfo() {
  // @@protoc_insertion_point(field_mutable_list:db_protobuf.db_loginallserverinfo.allserverinfo)
  return &allserverinfo_;
}
inline const ::google::protobuf::RepeatedPtrField< ::db_protobuf::serverinfo >&
db_loginallserverinfo::allserverinfo() const {
  // @@protoc_insertion_point(field_list:db_protobuf.db_loginallserverinfo.allserverinfo)
  return allserverinfo_;
}

inline const db_loginallserverinfo* db_loginallserverinfo::internal_default_instance() {
  return &db_loginallserverinfo_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db_protobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_db_5fprotobuf_2eproto__INCLUDED
