// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_struct.proto

#ifndef PROTOBUF_proto_5fstruct_2eproto__INCLUDED
#define PROTOBUF_proto_5fstruct_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5fstruct_2eproto();
void protobuf_AssignDesc_proto_5fstruct_2eproto();
void protobuf_ShutdownFile_proto_5fstruct_2eproto();

class struct_serverList;

// ===================================================================

class struct_serverList : public ::google::protobuf::Message {
 public:
  struct_serverList();
  virtual ~struct_serverList();

  struct_serverList(const struct_serverList& from);

  inline struct_serverList& operator=(const struct_serverList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const struct_serverList& default_instance();

  void Swap(struct_serverList* other);

  // implements Message ----------------------------------------------

  struct_serverList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const struct_serverList& from);
  void MergeFrom(const struct_serverList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string serverName = 1;
  inline bool has_servername() const;
  inline void clear_servername();
  static const int kServerNameFieldNumber = 1;
  inline const ::std::string& servername() const;
  inline void set_servername(const ::std::string& value);
  inline void set_servername(const char* value);
  inline void set_servername(const char* value, size_t size);
  inline ::std::string* mutable_servername();
  inline ::std::string* release_servername();
  inline void set_allocated_servername(::std::string* servername);

  // optional int32 serverId = 2;
  inline bool has_serverid() const;
  inline void clear_serverid();
  static const int kServerIdFieldNumber = 2;
  inline ::google::protobuf::int32 serverid() const;
  inline void set_serverid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:struct_serverList)
 private:
  inline void set_has_servername();
  inline void clear_has_servername();
  inline void set_has_serverid();
  inline void clear_has_serverid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* servername_;
  ::google::protobuf::int32 serverid_;
  friend void  protobuf_AddDesc_proto_5fstruct_2eproto();
  friend void protobuf_AssignDesc_proto_5fstruct_2eproto();
  friend void protobuf_ShutdownFile_proto_5fstruct_2eproto();

  void InitAsDefaultInstance();
  static struct_serverList* default_instance_;
};
// ===================================================================


// ===================================================================

// struct_serverList

// optional string serverName = 1;
inline bool struct_serverList::has_servername() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void struct_serverList::set_has_servername() {
  _has_bits_[0] |= 0x00000001u;
}
inline void struct_serverList::clear_has_servername() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void struct_serverList::clear_servername() {
  if (servername_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    servername_->clear();
  }
  clear_has_servername();
}
inline const ::std::string& struct_serverList::servername() const {
  // @@protoc_insertion_point(field_get:struct_serverList.serverName)
  return *servername_;
}
inline void struct_serverList::set_servername(const ::std::string& value) {
  set_has_servername();
  if (servername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    servername_ = new ::std::string;
  }
  servername_->assign(value);
  // @@protoc_insertion_point(field_set:struct_serverList.serverName)
}
inline void struct_serverList::set_servername(const char* value) {
  set_has_servername();
  if (servername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    servername_ = new ::std::string;
  }
  servername_->assign(value);
  // @@protoc_insertion_point(field_set_char:struct_serverList.serverName)
}
inline void struct_serverList::set_servername(const char* value, size_t size) {
  set_has_servername();
  if (servername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    servername_ = new ::std::string;
  }
  servername_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:struct_serverList.serverName)
}
inline ::std::string* struct_serverList::mutable_servername() {
  set_has_servername();
  if (servername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    servername_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:struct_serverList.serverName)
  return servername_;
}
inline ::std::string* struct_serverList::release_servername() {
  clear_has_servername();
  if (servername_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = servername_;
    servername_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void struct_serverList::set_allocated_servername(::std::string* servername) {
  if (servername_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete servername_;
  }
  if (servername) {
    set_has_servername();
    servername_ = servername;
  } else {
    clear_has_servername();
    servername_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:struct_serverList.serverName)
}

// optional int32 serverId = 2;
inline bool struct_serverList::has_serverid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void struct_serverList::set_has_serverid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void struct_serverList::clear_has_serverid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void struct_serverList::clear_serverid() {
  serverid_ = 0;
  clear_has_serverid();
}
inline ::google::protobuf::int32 struct_serverList::serverid() const {
  // @@protoc_insertion_point(field_get:struct_serverList.serverId)
  return serverid_;
}
inline void struct_serverList::set_serverid(::google::protobuf::int32 value) {
  set_has_serverid();
  serverid_ = value;
  // @@protoc_insertion_point(field_set:struct_serverList.serverId)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fstruct_2eproto__INCLUDED
